// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARtumBT8ckEDLx9X2IYA8vfzHTrf_ofBo',
    appId: '1:917068683588:android:c2a336732a1596c17ddf11',
    messagingSenderId: '917068683588',
    projectId: 'orgaflow-app',
    storageBucket: 'orgaflow-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr3yASsDnsYFNWHB2KEhkwTFPbwVdh1Z0',
    appId: '1:917068683588:ios:763ba06b6a5d47577ddf11',
    messagingSenderId: '917068683588',
    projectId: 'orgaflow-app',
    storageBucket: 'orgaflow-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterOrgaflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr3yASsDnsYFNWHB2KEhkwTFPbwVdh1Z0',
    appId: '1:917068683588:ios:763ba06b6a5d47577ddf11',
    messagingSenderId: '917068683588',
    projectId: 'orgaflow-app',
    storageBucket: 'orgaflow-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterOrgaflow',
  );
}
